version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
      - media_volume:/usr/src/app/media
    ports:
      - "8000:8000"
    restart: on-failure

volumes:
  media_volume: